name: "Waka - Node"
author: Amal Shan k
description: "Add a Wakatime Coding Activity graph in your Readme"

inputs:
  WAKATIME_API_KEY:
    description: "Your Wakatime/Wakapi/Hakatime API Key"
    required: true

  WK_URL:
    description: "Aternative API base URL when using a third-party WakaTime backend"
    required: true
  GH_TOKEN:
    description: "Github Token"
    required: true
    default: ${{ github.token }}

runs:
  using: "docker"
  image: "Dockerfile"
